package cs

import (
	"context"
	"fmt"
	"strings"
	"sync"

	"go.mau.fi/whatsmeow/types"

	"wakupi/internal/ai"
)

// CSConfig holds the CS Bot's own AI provider configuration, completely
// separate from the personal AI settings (stores/ai.ts / app.go AI config).
type CSConfig struct {
	Provider     string `json:"provider"`
	APIKey       string `json:"apiKey"`
	BaseURL      string `json:"baseUrl"`
	Model        string `json:"model"`
	Enabled      bool   `json:"enabled"`
	SystemPrompt string `json:"systemPrompt"`
	GreetingMsg  string `json:"greetingMsg"`
	UseGreeting  bool   `json:"useGreeting"`
}

// DefaultSystemPrompt is the default customer-service persona used when
// the user has not provided a custom prompt.
const DefaultSystemPrompt = `Kamu adalah customer service yang ramah, profesional, dan solutif.

Aturan:
- Balas dengan sopan dan informatif dalam bahasa Indonesia.
- Jangan mengaku sebagai entitas lain — kamu adalah asisten CS dari akun ini.
- Jika ditanya di luar konteks layanan yang kamu tahu, arahkan untuk menghubungi admin.
- Jawab singkat, padat, jelas, maksimal 3 kalimat.
- Jangan gunakan emoji berlebihan. Maksimal 1 emoji per balasan.
- Jika pengguna mengucapkan terima kasih, balas dengan "Sama-sama! Ada yang bisa kami bantu lagi?"`

// SendFunc is the function signature for sending a text reply back to a
// WhatsApp chat. It is provided by the caller (app.go) so the cs package
// does not need to depend on the full wa.Session.
type SendFunc func(ctx context.Context, jid types.JID, text string) error

// MessageContext carries the minimal information the bot needs about an
// incoming message to generate a reply.
type MessageContext struct {
	ChatJID  types.JID
	Text     string
	PushName string
}

// Bot is an AI-powered customer-service auto-reply bot. It holds its own
// ai.Service instance so its provider/model/key are independent of the
// personal AI settings used in the Playground.
type Bot struct {
	mu      sync.RWMutex
	cfg     CSConfig
	service *ai.Service

	// greeted tracks which chat JIDs have received the optional greeting
	// message so it's only sent once per chat.
	greetedMu sync.Mutex
	greeted   map[string]bool
}

// New creates a CS Bot from the given config.
func New(cfg CSConfig) *Bot {
	b := &Bot{
		greeted: make(map[string]bool),
	}
	b.rebuildService(cfg)
	return b
}

// rebuildService creates a fresh ai.Service from the provided config.
func (b *Bot) rebuildService(cfg CSConfig) {
	ac := ai.Config{
		Provider: ai.Provider(cfg.Provider),
		APIKey:   cfg.APIKey,
		BaseURL:  cfg.BaseURL,
		Model:    cfg.Model,
		Enabled:  cfg.Enabled,
	}
	b.service = ai.New(ac)
	b.cfg = cfg
}

// Update replaces the bot's config and rebuilds the internal ai.Service.
func (b *Bot) Update(cfg CSConfig) {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.rebuildService(cfg)
}

// Config returns a copy of the current config with the API key masked.
func (b *Bot) Config() CSConfig {
	b.mu.RLock()
	defer b.mu.RUnlock()
	c := b.cfg
	if c.APIKey != "" {
		c.APIKey = strings.Repeat("*", 8)
	}
	return c
}

// Enabled returns true when the bot is enabled and the underlying AI
// service can make requests.
func (b *Bot) Enabled() bool {
	b.mu.RLock()
	defer b.mu.RUnlock()
	return b.service.Enabled()
}

// Ping tests the CS Bot's provider connection without sending a message.
func (b *Bot) Ping(ctx context.Context) error {
	b.mu.RLock()
	svc := b.service
	b.mu.RUnlock()
	return svc.Ping(ctx)
}

// HandleMessage processes an incoming message and sends an auto-reply if
// the bot is enabled. It is designed to be called from a goroutine so the
// main message pipeline is not blocked.
//
// send is the function that delivers the reply text to the chat. It should
// be provided by the caller with the correct session reference.
//
// The reply is generated by the CS Bot's own AI service (separate provider
// and model from the personal AI) using the configured system prompt.
func (b *Bot) HandleMessage(ctx context.Context, mc MessageContext, send SendFunc) {
	b.mu.RLock()
	svc := b.service
	cfg := b.cfg
	b.mu.RUnlock()

	if !svc.Enabled() {
		return
	}
	if mc.Text == "" {
		return
	}

	// Optional greeting: send once per chat.
	if cfg.UseGreeting && cfg.GreetingMsg != "" {
		b.greetedMu.Lock()
		already := b.greeted[mc.ChatJID.String()]
		if !already {
			b.greeted[mc.ChatJID.String()] = true
		}
		b.greetedMu.Unlock()
		if !already && send != nil {
			_ = send(ctx, mc.ChatJID, cfg.GreetingMsg)
			return // wait for next message to give a real answer
		}
	}

	// Build AI prompt: use configured system prompt (or default).
	sysPrompt := cfg.SystemPrompt
	if sysPrompt == "" {
		sysPrompt = DefaultSystemPrompt
	}
	userPrompt := fmt.Sprintf(
		"Pesan dari %s:\n\n%s",
		mc.PushName, mc.Text,
	)

	reply, err := svc.Chat(ctx, sysPrompt, userPrompt)
	if err != nil {
		// Log the error but don't expose internal details to the contact.
		fmt.Printf("csbot: chat error: %v\n", err)
		return
	}
	reply = strings.TrimSpace(reply)
	if reply == "" {
		return
	}

	if send != nil {
		_ = send(ctx, mc.ChatJID, reply)
	}
}
