// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIChat'](arg1, arg2, arg3);
}

export function AIChatCancel() {
  return window['go']['main']['App']['AIChatCancel']();
}

export function AICompose(arg1, arg2) {
  return window['go']['main']['App']['AICompose'](arg1, arg2);
}

export function AIGenerateImage(arg1, arg2) {
  return window['go']['main']['App']['AIGenerateImage'](arg1, arg2);
}

export function AIGetGamAPIModels() {
  return window['go']['main']['App']['AIGetGamAPIModels']();
}

export function AIGetGamAPIRatios() {
  return window['go']['main']['App']['AIGetGamAPIRatios']();
}

export function AIGetGamAPIStyles() {
  return window['go']['main']['App']['AIGetGamAPIStyles']();
}

export function AIListModels(arg1) {
  return window['go']['main']['App']['AIListModels'](arg1);
}

export function AISuggestReplies(arg1, arg2) {
  return window['go']['main']['App']['AISuggestReplies'](arg1, arg2);
}

export function AISummarize(arg1) {
  return window['go']['main']['App']['AISummarize'](arg1);
}

export function AITestConnection(arg1) {
  return window['go']['main']['App']['AITestConnection'](arg1);
}

export function ArchiveChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ArchiveChat'](arg1, arg2, arg3);
}

export function BlockChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['BlockChat'](arg1, arg2, arg3);
}

export function CSBotTestConnection(arg1) {
  return window['go']['main']['App']['CSBotTestConnection'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ForwardMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ForwardMessage'](arg1, arg2, arg3, arg4);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetCSBotConfig() {
  return window['go']['main']['App']['GetCSBotConfig']();
}

export function GetGroupInfo(arg1, arg2) {
  return window['go']['main']['App']['GetGroupInfo'](arg1, arg2);
}

export function GetImageGenConfig() {
  return window['go']['main']['App']['GetImageGenConfig']();
}

export function ImageGenTestConnection(arg1) {
  return window['go']['main']['App']['ImageGenTestConnection'](arg1);
}

export function IsOnWhatsApp(arg1, arg2) {
  return window['go']['main']['App']['IsOnWhatsApp'](arg1, arg2);
}

export function LeaveGroup(arg1, arg2) {
  return window['go']['main']['App']['LeaveGroup'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListStarred(arg1, arg2) {
  return window['go']['main']['App']['ListStarred'](arg1, arg2);
}

export function LoadChats(arg1) {
  return window['go']['main']['App']['LoadChats'](arg1);
}

export function LoadMessages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoadMessages'](arg1, arg2, arg3, arg4);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function MarkRead(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MarkRead'](arg1, arg2, arg3, arg4);
}

export function MarketGetChart(arg1, arg2) {
  return window['go']['main']['App']['MarketGetChart'](arg1, arg2);
}

export function MarketGetQuote(arg1) {
  return window['go']['main']['App']['MarketGetQuote'](arg1);
}

export function MarketGetQuotes(arg1) {
  return window['go']['main']['App']['MarketGetQuotes'](arg1);
}

export function MediaHTTPHandler() {
  return window['go']['main']['App']['MediaHTTPHandler']();
}

export function MuteChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['MuteChat'](arg1, arg2, arg3);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function PinChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['PinChat'](arg1, arg2, arg3);
}

export function PostStatusImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['PostStatusImage'](arg1, arg2, arg3);
}

export function PostStatusText(arg1, arg2) {
  return window['go']['main']['App']['PostStatusText'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReactMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReactMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function RefreshAvatar(arg1, arg2) {
  return window['go']['main']['App']['RefreshAvatar'](arg1, arg2);
}

export function SaveBase64Image(arg1) {
  return window['go']['main']['App']['SaveBase64Image'](arg1);
}

export function SaveTempBlob(arg1, arg2) {
  return window['go']['main']['App']['SaveTempBlob'](arg1, arg2);
}

export function SearchMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMessages'](arg1, arg2, arg3);
}

export function SendAudio(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendAudio'](arg1, arg2, arg3, arg4, arg5);
}

export function SendChatPresence(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatPresence'](arg1, arg2, arg3);
}

export function SendDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendDocument'](arg1, arg2, arg3, arg4);
}

export function SendImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendImage'](arg1, arg2, arg3, arg4, arg5);
}

export function SendText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendText'](arg1, arg2, arg3, arg4);
}

export function SendVideo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendVideo'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAIConfig(arg1) {
  return window['go']['main']['App']['SetAIConfig'](arg1);
}

export function SetCSBotConfig(arg1) {
  return window['go']['main']['App']['SetCSBotConfig'](arg1);
}

export function SetGroupName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGroupName'](arg1, arg2, arg3);
}

export function SetImageGenConfig(arg1) {
  return window['go']['main']['App']['SetImageGenConfig'](arg1);
}

export function SetSelfProfilePicture(arg1, arg2) {
  return window['go']['main']['App']['SetSelfProfilePicture'](arg1, arg2);
}

export function SetSelfStatus(arg1, arg2) {
  return window['go']['main']['App']['SetSelfStatus'](arg1, arg2);
}

export function StarMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StarMessage'](arg1, arg2, arg3, arg4);
}

export function StartLogin(arg1) {
  return window['go']['main']['App']['StartLogin'](arg1);
}

export function SubscribePresence(arg1, arg2) {
  return window['go']['main']['App']['SubscribePresence'](arg1, arg2);
}

export function UpdateGroupParticipants(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateGroupParticipants'](arg1, arg2, arg3, arg4);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
